import fs from "node:fs";
import path from "node:path";

const replacements = new Map([
	["Turnstile failed to load", "No se pudo cargar Turnstile"],
	["Passwords do not match", "Las contraseñas no coinciden"],
	["Could not reset the password", "No se pudo restablecer la contraseña"],
	["Unable to reach the server. Please try again.", "No se pudo conectar con el servidor. Inténtalo de nuevo."],
	["Reset link missing", "Falta el enlace de restablecimiento"],
	["Open the link from the reset email to choose a new password.", "Abre el enlace del correo de restablecimiento para elegir una contraseña nueva."],
	["Password updated", "Contraseña actualizada"],
	["Choose a new password", "Elige una contraseña nueva"],
	["You have been signed out everywhere. Sign in with your new password to continue.", "Se cerró tu sesión en todos los dispositivos. Inicia sesión con tu contraseña nueva para continuar."],
	["Use at least 8 characters. Every other session for this account will be signed out.", "Usa al menos 8 caracteres. Se cerrarán las demás sesiones de esta cuenta."],
	["New password", "Contraseña nueva"],
	["Confirm new password", "Confirma la contraseña nueva"],
	["Saving...", "Guardando..."],
	["Set new password", "Establecer contraseña nueva"],
	["Something went wrong. Please try again.", "Ocurrió un problema. Inténtalo de nuevo."],
	["Reset your password", "Restablece tu contraseña"],
	["If that account has a recovery email, a reset link is on its way. It works for 30 minutes.", "Si esa cuenta tiene un correo de recuperación, recibirás un enlace de restablecimiento. Será válido por 30 minutos."],
	["Enter the address you sign in with. We will send a reset link to the recovery email on the account.", "Ingresa la dirección con la que inicias sesión. Enviaremos un enlace al correo de recuperación de la cuenta."],
	["Email", "Correo electrónico"],
	["Sending...", "Enviando..."],
	["Send reset link", "Enviar enlace de restablecimiento"],
	["Could not load setup status", "No se pudo cargar el estado de configuración"],
	["Could not check existing MX records", "No se pudieron comprobar los registros MX existentes"],
	["Complete the missing configuration before continuing.", "Completa la configuración pendiente antes de continuar."],
	["Installation preparation failed", "No se pudo preparar la instalación"],
	["Domain setup failed", "No se pudo configurar el dominio"],
	["Domain check failed", "No se pudo comprobar el dominio"],
	["Domain setup is not complete", "La configuración del dominio no está completa"],
	["Registration failed", "No se pudo completar el registro"],
	["Account registration is closed", "El registro de cuentas está cerrado"],
	["this workspace", "este espacio de trabajo"],
	["Prepare installation", "Preparar instalación"],
	["Add your domain", "Agrega tu dominio"],
	["Create your mailbox", "Crea tu buzón"],
	["System", "Sistema"],
	["Domain", "Dominio"],
	["Account", "Cuenta"],
	["Clean database migrated successfully", "La base de datos limpia se migró correctamente"],
	["Database schema is ready", "El esquema de la base de datos está listo"],
	["Checking...", "Comprobando..."],
	["Check again", "Comprobar de nuevo"],
	["Primary domain", "Dominio principal"],
	["Enable sending", "Activar envío"],
	["Checking Cloudflare access...", "Comprobando el acceso a Cloudflare..."],
	["Required to send email.", "Necesario para enviar correos."],
	["Receive-only mode.", "Modo de solo recepción."],
	["Enter the domain and leave the field to verify it.", "Ingresa el dominio y sal del campo para verificarlo."],
	["Adding domain...", "Agregando dominio..."],
	["Continue", "Continuar"],
	["Username", "Nombre de usuario"],
	["Password", "Contraseña"],
	["Recovery email", "Correo de recuperación"],
	["Creating...", "Creando..."],
	["Create account", "Crear cuenta"],
	["Login failed", "No se pudo iniciar sesión"],
	["Login timed out. Please try again.", "El inicio de sesión agotó el tiempo de espera. Inténtalo de nuevo."],
	["Unable to reach the login service. Please try again.", "No se pudo conectar con el servicio de inicio de sesión. Inténtalo de nuevo."],
	["That code did not match", "Ese código no coincide"],
	["Two-factor authentication", "Autenticación de dos factores"],
	["Enter the 6-digit code from your authenticator app, or one of your recovery codes.", "Ingresa el código de 6 dígitos de tu aplicación de autenticación o uno de tus códigos de recuperación."],
	["Code", "Código"],
	["Verifying...", "Verificando..."],
	["Verify", "Verificar"],
	["Sign in", "Iniciar sesión"],
	["Open your mailbox and continue from the same inbox workspace.", "Abre tu buzón y continúa desde el mismo espacio de la bandeja de entrada."],
	["Forgot password?", "¿Olvidaste tu contraseña?"],
	["Signing in...", "Iniciando sesión..."],
	["Failed to add domain", "No se pudo agregar el dominio"],
	["Failed to create mailbox", "No se pudo crear el buzón"],
	["Connect mail routing", "Conecta el enrutamiento de correo"],
	["Create your first mailbox", "Crea tu primer buzón"],
	["Add the Cloudflare domain that will receive mail and optionally send through this workspace.", "Agrega el dominio de Cloudflare que recibirá correo y, de forma opcional, enviará desde este espacio de trabajo."],
	["Choose the mailbox address that should open directly into the inbox.", "Elige la dirección del buzón que debe abrir directamente la bandeja de entrada."],
	["Mailbox", "Buzón"],
	["Leave the domain field to verify it.", "Sal del campo de dominio para verificarlo."],
	["Replacing MX records...", "Reemplazando registros MX..."],
	["Delete MX records and continue", "Eliminar registros MX y continuar"],
	["Adding...", "Agregando..."],
	["Add domain", "Agregar dominio"],
	["Mailbox address", "Dirección del buzón"],
	["Go to inbox", "Ir a la bandeja de entrada"],
	["Request a new link", "Solicitar un enlace nuevo"],
	["Go to sign in", "Ir a iniciar sesión"],
	["Back to sign in", "Volver a iniciar sesión"],
	["Sign in instead", "Iniciar sesión en su lugar"],
	["This installation already has an account for", "Esta instalación ya tiene una cuenta para"],
	["Go to login", "Ir al inicio de sesión"],
	["Mailflare checks its required Cloudflare configuration and initializes a clean D1 database before setup continues.", "Mailflare comprueba la configuración necesaria de Cloudflare e inicializa una base de datos D1 limpia antes de continuar."],
	["Checking installation", "Comprobando la instalación"],
	["The domain must already be a Cloudflare zone on this account.", "El dominio ya debe ser una zona de Cloudflare en esta cuenta."],
	["Domain found in Cloudflare as", "Dominio encontrado en Cloudflare como"],
	["Checking existing MX records", "Comprobando los registros MX existentes"],
	["No existing MX records found", "No se encontraron registros MX existentes"],
	["Replace existing MX records", "Reemplazar los registros MX existentes"],
	["This deletes the current mail provider's MX records and replaces them with Cloudflare Email Routing. The previous provider will stop receiving mail.", "Esto elimina los registros MX del proveedor de correo actual y los reemplaza con Cloudflare Email Routing. El proveedor anterior dejará de recibir correo."],
	["Check MX records again", "Comprobar de nuevo los registros MX"],
	["Setup completes in the inbox", "La configuración termina en la bandeja de entrada"],
	["Your domain must use Cloudflare DNS on the same account as", "Tu dominio debe usar Cloudflare DNS en la misma cuenta que"],
	["Existing MX records deliver mail to another provider. Continuing deletes those records and replaces them with Cloudflare Email Routing, so the previous provider will stop receiving mail.", "Los registros MX existentes entregan el correo a otro proveedor. Si continúas, se eliminarán y se reemplazarán con Cloudflare Email Routing, por lo que el proveedor anterior dejará de recibir correo."],
	["Dominio found in Cloudflare as", "Dominio encontrado en Cloudflare como"],
	["Iniciar sesión instead", "Iniciar sesión en su lugar"],
	["This deletes the current mail provider's MX records and replaces them with Cloudflare Correo electrónico Routing. The previous provider will stop receiving mail.", "Esto elimina los registros MX del proveedor de correo actual y los reemplaza con Cloudflare Email Routing. El proveedor anterior dejará de recibir correo."],
	["Existing MX records deliver mail to another provider. Continuing deletes those records and replaces them with Cloudflare Correo electrónico Routing, so the previous provider will stop receiving mail.", "Los registros MX existentes entregan el correo a otro proveedor. Si continúas, se eliminarán y se reemplazarán con Cloudflare Email Routing, por lo que el proveedor anterior dejará de recibir correo."],
]);

const commonReplacements = new Map([
	["Multi-tenant email on Cloudflare", "Correo multiusuario en Cloudflare"],
	["Open dashboard", "Abrir panel"], ["View inbox", "Ver bandeja de entrada"],
	["Inbox", "Bandeja de entrada"], ["Sent", "Enviados"], ["Drafts", "Borradores"], ["Trash", "Papelera"],
	["Archive", "Archivar"], ["Starred", "Destacados"], ["Snoozed", "Pospuestos"], ["Compose", "Redactar"],
	["Reply", "Responder"], ["Reply all", "Responder a todos"], ["Forward", "Reenviar"], ["Send", "Enviar"],
	["Attachment", "Adjunto"], ["Shared inbox", "Buzón compartido"], ["Folder", "Carpeta"], ["Label", "Etiqueta"],
	["Search", "Buscar"], ["Settings", "Ajustes"], ["Sign out", "Cerrar sesión"], ["Auto-reply", "Respuesta automática"],
	["Contacts", "Contactos"], ["Calendar", "Calendario"], ["Backup", "Copia de seguridad"], ["Audit log", "Registro de auditoría"],
	["License", "Licencia"], ["Admin", "Administrador"], ["Save", "Guardar"], ["Cancel", "Cancelar"],
	["Delete", "Eliminar"], ["Edit", "Editar"], ["Loading...", "Cargando..."], ["No messages", "No hay mensajes"],
	["No drafts", "No hay borradores"], ["No results", "No hay resultados"], ["Create folder", "Crear carpeta"],
	["Folder color", "Color de la carpeta"], ["Expand menu", "Expandir menú"], ["Collapse menu", "Contraer menú"],
	["Archive Message", "Archivar mensaje"], ["Move to Trash", "Mover a Papelera"], ["Reply to Message", "Responder al mensaje"],
	["Report Spam", "Marcar como spam"], ["Back to List", "Volver a la lista"], ["Not spam", "No es spam"],
	["(no subject)", "(sin asunto)"], ["No subject", "Sin asunto"], ["Unknown sender", "Remitente desconocido"],
	["Select all", "Seleccionar todo"], ["Mark as read", "Marcar como leído"], ["Mark as unread", "Marcar como no leído"],
	["Move to folder", "Mover a carpeta"], ["Move", "Mover"], ["More", "Más"], ["Refresh", "Actualizar"],
	["Schedule send", "Programar envío"], ["Send now", "Enviar ahora"], ["Discard draft", "Descartar borrador"],
	["To", "Para"], ["Bcc", "Cco"], ["Subject", "Asunto"], ["Message", "Mensaje"],
	["Add attachment", "Agregar adjunto"], ["Remove attachment", "Quitar adjunto"], ["Close", "Cerrar"],
	["Add", "Agregar"], ["Update", "Actualizar"], ["Today", "Hoy"], ["Tomorrow", "Mañana"],
	["Next week", "La próxima semana"], ["Create event", "Crear evento"], ["Edit event", "Editar evento"],
	["Delete event", "Eliminar evento"], ["Event title", "Título del evento"], ["Delete this event?", "¿Eliminar este evento?"],
	["Start date and time", "Fecha y hora de inicio"], ["End date and time", "Fecha y hora de fin"],
	["Message not found", "Mensaje no encontrado"], ["Attachment not found", "Adjunto no encontrado"],
	["Draft not found", "Borrador no encontrado"], ["Account not found", "Cuenta no encontrada"],
	["Mailbox not found", "Buzón no encontrado"], ["Domain not found", "Dominio no encontrado"],
	["Folder not found", "Carpeta no encontrada"], ["Alias not found", "Alias no encontrado"],
	["Rule not found", "Regla no encontrada"], ["Event not found", "Evento no encontrado"],
	["Backup not found", "Copia de seguridad no encontrada"], ["Webhook not found", "Webhook no encontrado"],
	["Invalid request", "Solicitud no válida"], ["Invalid credentials", "Credenciales no válidas"],
	["Account disabled", "Cuenta desactivada"], ["Password is incorrect", "La contraseña es incorrecta"],
	["Current password is incorrect", "La contraseña actual es incorrecta"], ["Enter your password", "Ingresa tu contraseña"],
	["Account is required", "La cuenta es obligatoria"], ["Mailbox is required", "El buzón es obligatorio"],
	["Folder is required", "La carpeta es obligatoria"], ["Destination is required", "El destino es obligatorio"],
	["Alias is required", "El alias es obligatorio"], ["No changes provided", "No se indicaron cambios"],
	["No changes requested", "No se solicitaron cambios"], ["No accessible messages", "No hay mensajes accesibles"],
	["Folder already exists", "La carpeta ya existe"], ["Mailbox already exists", "El buzón ya existe"],
	["Email already registered", "El correo ya está registrado"], ["Message too large", "El mensaje es demasiado grande"],
	["Invalid signature", "Firma no válida"], ["Not available in production", "No disponible en producción"],
	["Update Mailflare", "Actualizar Mailflare"], ["Starting update...", "Iniciando actualización..."],
	["Updating database...", "Actualizando la base de datos..."], ["Update database", "Actualizar base de datos"],
	["Save settings", "Guardar ajustes"], ["Back up now", "Crear copia ahora"],
	["Enable automatic backups", "Activar copias de seguridad automáticas"],
	["Delete old backups automatically", "Eliminar automáticamente las copias antiguas"],
	["Download backup", "Descargar copia de seguridad"], ["Delete backup", "Eliminar copia de seguridad"],
	["Save branding", "Guardar identidad visual"], ["Create key", "Crear clave"],
	["Preparing...", "Preparando..."], ["Download .mbox", "Descargar .mbox"],
	["Remove inbox", "Quitar bandeja de entrada"], ["Add inbox", "Agregar bandeja de entrada"],
]);

const apiReplacements = new Map([
	["Unauthorized", "No autorizado"], ["Forbidden", "Prohibido"], ["Not found", "No encontrado"],
	["Expected multipart form data", "Se esperaban datos de formulario multipart"], ["Missing image file", "Falta el archivo de imagen"],
	["Use a JPEG, PNG, WebP, or GIF image", "Usa una imagen JPEG, PNG, WebP o GIF"], ["Image must be 2 MB or smaller", "La imagen debe pesar 2 MB o menos"],
	["Delivery not found", "Entrega no encontrada"], ["Invalid webhook request", "Solicitud de webhook no válida"],
	["Invalid draft request", "Solicitud de borrador no válida"], ["Invalid message status", "Estado de mensaje no válido"],
	["Invalid send request", "Solicitud de envío no válida"], ["Choose a future snooze time", "Elige una hora futura para posponer"],
	["Invalid bulk message action", "Acción masiva de mensajes no válida"], ["Initial setup is already complete", "La configuración inicial ya está completa"],
	["Backup file not found", "Archivo de copia de seguridad no encontrado"], ["Invalid backup settings", "Ajustes de copia de seguridad no válidos"],
	["A valid account name is required", "Se requiere un nombre de cuenta válido"],
	["Failed to configure inbound routing for all domains. Please try saving again.", "No se pudo configurar el enrutamiento entrante para todos los dominios. Intenta guardar de nuevo."],
	["Enter a title and valid event times", "Ingresa un título y horarios válidos para el evento"],
	["App name must be between 1 and 60 characters", "El nombre de la aplicación debe tener entre 1 y 60 caracteres"],
	["Use a PNG, JPEG, WebP, or GIF image", "Usa una imagen PNG, JPEG, WebP o GIF"], ["Icon must be 2 MB or smaller", "El ícono debe pesar 2 MB o menos"],
	["Choose a backup file", "Elige un archivo de copia de seguridad"], ["Enter a valid alias username and domain", "Ingresa un nombre de usuario y dominio válidos para el alias"],
	["A mailbox already uses this address", "Un buzón ya usa esta dirección"], ["An alias already uses this address", "Un alias ya usa esta dirección"],
	["Failed to create the Cloudflare Email Routing rule for this alias. Please try again.", "No se pudo crear la regla de Cloudflare Email Routing para este alias. Inténtalo de nuevo."],
	["Failed to remove the Cloudflare Email Routing rule for this alias. Please try again.", "No se pudo eliminar la regla de Cloudflare Email Routing para este alias. Inténtalo de nuevo."],
	["Mailbox and contact are required", "El buzón y el contacto son obligatorios"], ["A valid contact name is required", "Se requiere un nombre de contacto válido"],
	["Only the account owner can change this contact", "Solo el propietario de la cuenta puede modificar este contacto"],
	["Shared inbox not found", "Buzón compartido no encontrado"], ["Choose a valid account", "Elige una cuenta válida"],
	["A Team license is required to create shared inboxes", "Se requiere una licencia Team para crear buzones compartidos"],
	["Registration is closed after the first account is created", "El registro se cierra después de crear la primera cuenta"],
	["Invalid registration request", "Solicitud de registro no válida"], ["Verification failed. Please try again.", "La verificación falló. Inténtalo de nuevo."],
	["Primary domain already exists", "El dominio principal ya existe"], ["Invalid setup request", "Solicitud de configuración no válida"],
	["Enter a valid license key", "Ingresa una clave de licencia válida"], ["Invalid MX check request", "Solicitud de comprobación MX no válida"],
	["New password must be different from the current password", "La contraseña nueva debe ser distinta de la actual"],
	["Mailbox, contact, and image file are required", "El buzón, el contacto y el archivo de imagen son obligatorios"],
	["domainId is required", "domainId es obligatorio"], ["Domain or mailbox access is required", "Se requiere acceso al dominio o al buzón"],
	["Mailbox access is required for the destination", "Se requiere acceso al buzón de destino"],
	["Enter the email address you sign in with", "Ingresa la dirección de correo con la que inicias sesión"],
	["Too many attempts. Try again shortly.", "Demasiados intentos. Inténtalo de nuevo en unos minutos."],
	["A Pro or Team license is required for email forwarding", "Se requiere una licencia Pro o Team para reenviar correos"],
	["Choose Pro or Team", "Elige Pro o Team"], ["Choose a password of at least 8 characters", "Elige una contraseña de al menos 8 caracteres"],
	["Enter the 6-digit code", "Ingresa el código de 6 dígitos"], ["Two-factor authentication is off", "La autenticación de dos factores está desactivada"],
	["Enter your password and a code", "Ingresa tu contraseña y un código"], ["Two-factor authentication is already on", "La autenticación de dos factores ya está activada"],
	["This sign-in attempt has expired. Start again.", "Este intento de inicio de sesión venció. Empieza de nuevo."],
	["Invalid import upload", "Carga de importación no válida"], ["Select a mailbox and at least one .eml or .mbox file", "Selecciona un buzón y al menos un archivo .eml o .mbox"],
	["A Team license is required to manage accounts", "Se requiere una licencia Team para administrar cuentas"],
	["Email address is already assigned", "La dirección de correo ya está asignada"], ["Invalid login request", "Solicitud de inicio de sesión no válida"],
	["Too many login attempts. Try again shortly.", "Demasiados intentos de inicio de sesión. Inténtalo de nuevo en unos minutos."],
	["Multiple accounts are not available in this build", "Esta versión no permite varias cuentas"], ["Invalid request origin", "Origen de la solicitud no válido"],
]);

for (const root of process.argv.slice(2)) {
	const files = [];
	const visit = (entry) => {
		const stat = fs.statSync(entry);
		if (stat.isDirectory()) {
			for (const child of fs.readdirSync(entry)) visit(path.join(entry, child));
		} else if (/\.(?:ts|tsx)$/.test(entry)) files.push(entry);
	};
	visit(root);
	for (const file of files) {
		const original = fs.readFileSync(file, "utf8");
		let next = original;
		const selected = file.includes(`${path.sep}api${path.sep}`)
			? [...replacements, ...commonReplacements, ...apiReplacements]
			: file.endsWith(".tsx") ? [...replacements, ...commonReplacements] : replacements;
		for (const [english, spanish] of selected) {
			next = next.replaceAll(`"${english}"`, `"${spanish}"`);
			if (file.endsWith(".tsx")) {
				const escaped = english.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
				next = next.replace(new RegExp(`(>\\s*)${escaped}(\\s*<)`, "g"), `$1${spanish}$2`);
			}
		}
		if (next !== original) fs.writeFileSync(file, next, "utf8");
	}
}
